version: "3.7"
services:
  spring_api_service:
    build: .
    image: spring-image
    restart: always
    ports:
      - "8080:8080"
    networks:
      - spring-mysql-net
    depends_on:
      - mysqldb

  mysqldb:
    image: "mysql:8.0"
    restart: always
    ports:
      - "3306:3306"
    networks:
      - spring-mysql-net
    environment:
      MYSQL_DATABASE: db_name
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root_password
networks:
  spring-mysql-net:
